USE [master]
GO
/****** Object:  Database [SampleMvc]    Script Date: 10/05/2016 15:44:02 ******/
CREATE DATABASE [SampleMvc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleMvc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SampleMvc.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SampleMvc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SampleMvc_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SampleMvc] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SampleMvc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SampleMvc] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SampleMvc] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SampleMvc] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SampleMvc] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SampleMvc] SET ARITHABORT OFF 
GO
ALTER DATABASE [SampleMvc] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SampleMvc] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [SampleMvc] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SampleMvc] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SampleMvc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SampleMvc] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SampleMvc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SampleMvc] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SampleMvc] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SampleMvc] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SampleMvc] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SampleMvc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SampleMvc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SampleMvc] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SampleMvc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SampleMvc] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SampleMvc] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SampleMvc] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SampleMvc] SET RECOVERY FULL 
GO
ALTER DATABASE [SampleMvc] SET  MULTI_USER 
GO
ALTER DATABASE [SampleMvc] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SampleMvc] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SampleMvc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SampleMvc] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [SampleMvc]
GO
/****** Object:  StoredProcedure [dbo].[spClearAllData]    Script Date: 10/05/2016 15:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[spClearAllData] 

AS
BEGIN
    DELETE FROM Product;
	DBCC CHECKIDENT ('[Product]', RESEED, 0);
	DELETE FROM Category;
	DBCC CHECKIDENT ('[Category]', RESEED, 0);
END

GO
/****** Object:  StoredProcedure [dbo].[spSetReferenceData]    Script Date: 10/05/2016 15:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spSetReferenceData] 

AS
BEGIN
	INSERT INTO Category (Name) VALUES ('Books'), ('CDs'), ('DVDs') 
END
GO
/****** Object:  Table [dbo].[Category]    Script Date: 10/05/2016 15:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](80) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Product]    Script Date: 10/05/2016 15:44:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryId] [int] NOT NULL,
	[Name] [nvarchar](80) NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([CategoryId])
GO
USE [master]
GO
ALTER DATABASE [SampleMvc] SET  READ_WRITE 
GO
